### ISSUE TITLE
RSS links are wrong

### ISSUE THREAD

**Issue by allanderek** [ValeLang/Site#71]
I am subscribed to the RSS feed at: https://verdagon.dev/rss.xml but I believe is the same (or at least the same code) at: https://vale.dev/rss.xml

It is producing links such as: https://verdagon.dev/blog/blog/zero-cost-memory-safety-regions-overview
which result in a 404. I think they just have an extra /blog path element, so it should be: https://verdagon.dev/blog/zero-cost-memory-safety-regions-overview

**Comment by Verdagon** [comment]
Fixed, thank you so much!
